language: python
sudo: enabled
services:
  - mysql
env:
  global:
    - TRAVIS=true
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS wechat_ticket;'
  - mv configs.example.json configs.json
install:
  - pip install -r requirements.txt
script:
  - pytest
